# Generated by Django 4.2.7 on 2026-04-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceimage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='min_size',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='userupload_name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='serviceimage',
            table='service_images',
        ),
    ]
