# Generated by Django 5.0.6 on 2026-04-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_serviceimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceimage',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
