# Generated by Django 4.2.7 on 2026-03-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_artist_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
