# Generated by Django 5.0.6 on 2026-04-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='kyc_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='artist',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
