# Generated by Django 5.0.6 on 2026-04-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_artist_kyc_status_artist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
