# Generated by Django 4.2.7 on 2026-04-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_booking_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='status',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='artist',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
